// GENERATED by generate_rules.py from utils/Engineer_Style.py — do not edit.
// Re-run `python generate_rules.py` after changing the Pygments lexer.
export const DSL_RULES = [
  {
    "pattern": ":=|≔|←",
    "cls": "edsl-op"
  },
  {
    "pattern": "(\\d+)(\\.\\.)(?!\\.)",
    "groups": [
      "edsl-number",
      "edsl-op"
    ]
  },
  {
    "pattern": "(?<!\\.)(\\.\\.)(?!\\.)(\\s*)([+-]?)(\\d+(?:\\.\\d*)?(?:[eE][+-]?\\d+)?|\\.\\d+)",
    "groups": [
      "edsl-op",
      null,
      "edsl-op",
      "edsl-number"
    ]
  },
  {
    "pattern": "‥|(?<!\\.)\\.\\.(?!\\.)",
    "cls": "edsl-op"
  },
  {
    "pattern": "▶|▸",
    "cls": "edsl-op"
  },
  {
    "pattern": "→",
    "cls": "edsl-opword"
  },
  {
    "pattern": "ₜᵢₘₑ|ᵣₒₘₑ",
    "cls": "edsl-opword"
  },
  {
    "pattern": "‖|±|∠|≈",
    "cls": "edsl-op"
  },
  {
    "pattern": "∅",
    "cls": "edsl-constkw"
  },
  {
    "pattern": "∈|∉|∋|∌|∪|∩|∖|△|⊕|⊆|⊇|⊂|⊃",
    "cls": "edsl-op"
  },
  {
    "pattern": "∑|∏",
    "cls": "edsl-helper"
  },
  {
    "pattern": "°[CFR](?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-unit"
  },
  {
    "pattern": "℃|℉",
    "cls": "edsl-unit"
  },
  {
    "pattern": "°|²|³|√|⌊|⌋|⌈|⌉|‰|×|÷|·|⋅|−|≤|≥|≠|∞|↑|ᵀ|!(?!=)",
    "cls": "edsl-op"
  },
  {
    "pattern": "[⇥⭾↵⏎↩⮐]",
    "cls": "edsl-strescape"
  },
  {
    "pattern": "[½⅓¼¾⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞]",
    "cls": "edsl-number"
  },
  {
    "pattern": "[₀₁₂₃₄₅₆₇₈₉₊₋₍₎ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓᵦᵧᵨᵩᵪ͵]+",
    "cls": "edsl-subsup"
  },
  {
    "pattern": "[⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁽⁾˙ᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻ]+",
    "cls": "edsl-subsup"
  },
  {
    "pattern": "(?<![A-Za-z_0-9])([0-9][0-9a-fA-F]*)([₀₁₂₃₄₅₆₇₈₉]+)",
    "groups": [
      "edsl-number",
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![A-Za-z_0-9])([a-fA-F]+)(₁₆)",
    "groups": [
      "edsl-number",
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:R_jupiter|M_jupiter|R_earth|M_earth|M_moon|R_sun|L_sun|R_gas|T_sun|M_sun|Rᵍᵃˢ|q_e|inf|m_n|N_A|k_B|m_p|µ_0|μ_0|g_n|ε_0|T_0|m_e|g_0|M♃|qₑ|M⊙|mₑ|εₒ|pi|R♃|L⊙|Nᴬ|gₒ|gₙ|L☉|T☉|µₒ|R⊕|Tₒ|mₙ|oo|mₚ|M☉|R☉|kᵦ|M⊕|R⊙|μₒ|π|ħ|h|c|ℏ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-physical"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:hp_electrical|year_tropical|nautical_mile|year_julian|TeV_per_c2|MeV_per_c2|keV_per_c2|GeV_per_c2|eV_per_c2|GeV_per_c|hp_metric|keV_per_c|MeV_per_c|TeV_per_c|prefix_n|prefix_G|fl_oz_uk|eV_per_c|prefix_c|prefix_T|prefix_M|prefix_µ|prefix_d|prefix_k|prefix_p|lbf_inch|prefix_m|ozf_inch|fl_oz_us|prefix_μ|coulomb|deltaC|barrel|minute|ton_us|newton|deltaK|lbf_ft|deltaF|gal_uk|parsec|deltaK|ton_uk|gal_us|stone|litre|pt_uk|grain|liter|month|inH2O|μbarn|ubarn|qt_us|pt_us|abarn|qt_uk|pbarn|tonne|nbarn|fbarn|µbarn|mbarn|dyne|year|thou|mile|degF|degC|yard|barn|hour|week|kcal|inch|torr|degR|slug|knot|mmHg|mbar|TeV|BTU|ppm|GeV|hPa|µJy|μJy|dam|GHz|kyr|ozf|Nmm|MHz|hms|kHz|kNm|MNm|mJy|kph|GPa|Gpc|Cal|MeV|ozt|mNm|ksi|kgf|Ohm|ptm|mol|keV|mph|rad|day|amu|lbm|kpc|mil|bar|atm|Mpc|Gyr|EeV|PeV|MPa|HMS|lbf|cal|ptc|kWh|THz|Myr|kPa|uJy|erg|psi|Pa|ΔC|kΩ|MΩ|mm|mC|µF|mg|MV|kV|sr|au|nA|Jy|kW|lb|kg|µC|Da|GΩ|μA|µm|ns|kΩ|ks|nm|cc|pH|μV|hp|mΩ|gf|GW|ly|pF|μg|GΩ|µW|mL|Wh|yr|dm|ΔK|mW|ng|mH|µs|fm|μW|ΔK|GN|ft|mF|MJ|μH|Nm|cd|pc|MΩ|kC|μC|eV|pA|oz|µA|pC|km|µg|µN|GJ|MW|pV|ps|hm|μN|nV|kp|MN|Hz|μm|kA|ms|pm|mΩ|µV|ΔF|dL|nW|μs|kJ|mA|nF|nH|hr|μF|µH|nC|mV|fs|Wb|cm|kN|mN|K|Å|S|T|C|Ω|N|K|m|A|V|Å|J|F|W|H|Ω|g|s)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-unit"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:θ|ο|δ|Φ|ν|Δ|Θ|ρ|ζ|κ|ς|β|µ|ι|ε|υ|χ|τ|Λ|σ|μ|γ|α|ξ|φ|η|ψ|λ|ω|Ξ|Ψ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-greek"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:HKD|SEK|CAD|JPY|EUR|CNY|CZK|USD|INR|HKD|DKK|DKK|NOK|PLN|SEK|DKK|CZK|GBP|DKK|NOK|CHF|AUD)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-currency"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:positive_symbols|integer_symbols|complex_symbols|real_symbols|symbols)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-decl"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:update_currency_rates|set_decimal_literals|to_fahrenheit_from_K|get_decimal_literals|to_fahrenheit_from_K|clear_currency_cache|protect_constants|clear_protections|to_celsius_from_F|get_currency_rate|to_kelvin_from_F|protect_si_units|refresh_display|launch_palette|tolerance_unit|register_radix|list_protected|to_fahrenheit|rates_status|list_themes|protect_all|print_view|from_roman|to_celsius|sigfigs_of|from_degC|to_kelvin|from_degR|unprotect|from_degF|from_dB_v|nsimplify|from_dB_p|integrate|plusminus|in_units|simplify|it_grade|hardcopy|permille|Rational|parallel|to_roman|lambdify|measured|protect|to_dB_v|percent|linefit|to_dB_p|display|polyfit|approx|interp|factor|expand|base10|Matrix|base16|nsolve|phasor|Symbol|series|shaft|exact|zeros|atanh|polar|cross|log10|atan2|asinh|latex|clamp|base8|hypot|floor|roman|solve|limit|radix|base2|acosh|acos|plot|fact|rect|hole|norm|diag|tanh|cbrt|ceil|sinh|cosh|ones|bode|perm|atan|sign|sqrt|comb|mean|diff|asin|log2|exp|mod|sin|lcm|gcd|sym|dot|det|oct|tan|fmt|eye|cos|fit|dec|iso|Sig|hex|log|bin|pv|ln|pn|pp|Eq|Γ|σ|Σ|Π)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-helper"
  },
  {
    "pattern": "([A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK][A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK]*)(ᵀ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "groups": [
      null,
      "edsl-op"
    ]
  },
  {
    "pattern": "([A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK][A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK]*)([ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓᵦᵧᵨᵩᵪᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻ]+)",
    "groups": [
      null,
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![\\w.])\\d+\\.(?![\\d.\\w])",
    "cls": "edsl-number"
  },
  {
    "pattern": "(\\.\\.\\s*)('(?:[^'\\\\\\n]|\\\\.)*'|\"(?:[^\"\\\\\\n]|\\\\.)*\")",
    "groups": [
      null,
      "edsl-string"
    ]
  },
  {
    "pattern": "[A-Za-z_][A-Za-z0-9_]*(?=\\s*\\.\\.(?!\\.))",
    "cls": "edsl-plain"
  },
  {
    "pattern": "(\\.\\.\\s*)([A-Za-z_][A-Za-z0-9_]*)",
    "groups": [
      null,
      "edsl-plain"
    ]
  },
  {
    "pattern": "(?<![\\w.])(?:0[xX][0-9a-fA-F_]+|0[bB][01_]+|0[oO][0-7_]+|\\d[\\d_]*\\.?[\\d_]*(?:[eE][+-]?\\d+)?[jJ]?|\\.\\d[\\d_]*(?:[eE][+-]?\\d+)?[jJ]?)",
    "cls": "edsl-number"
  },
  {
    "pattern": "(?<![=<>!:+\\-*/%&|^@])=(?!=)",
    "cls": "edsl-op"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:and|as|assert|async|await|break|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|nonlocal|not|or|pass|raise|return|try|while|with|yield)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-keyword"
  },
  {
    "pattern": "[+\\-*/%<>=!&|^~]+",
    "cls": "edsl-op"
  }
];
