// GENERATED by generate_rules.py from utils/Engineer_Style.py — do not edit.
// Re-run `python generate_rules.py` after changing the Pygments lexer.
export const DSL_RULES = [
  {
    "pattern": ":=|≔|←",
    "cls": "edsl-op"
  },
  {
    "pattern": "(\\d+)(\\.\\.)(?!\\.)",
    "groups": [
      "edsl-number",
      "edsl-op"
    ]
  },
  {
    "pattern": "(?<!\\.)(\\.\\.)(?!\\.)(\\s*)([+-]?)(\\d+(?:\\.\\d*)?(?:[eE][+-]?\\d+)?|\\.\\d+)",
    "groups": [
      "edsl-op",
      null,
      "edsl-op",
      "edsl-number"
    ]
  },
  {
    "pattern": "‥|(?<!\\.)\\.\\.(?!\\.)",
    "cls": "edsl-op"
  },
  {
    "pattern": "▶|▸",
    "cls": "edsl-op"
  },
  {
    "pattern": "→",
    "cls": "edsl-opword"
  },
  {
    "pattern": "ₜᵢₘₑ|ᵣₒₘₑ",
    "cls": "edsl-opword"
  },
  {
    "pattern": "‖|±|∠|≈",
    "cls": "edsl-op"
  },
  {
    "pattern": "∅",
    "cls": "edsl-constkw"
  },
  {
    "pattern": "∈|∉|∋|∌|∪|∩|∖|△|⊕|⊆|⊇|⊂|⊃",
    "cls": "edsl-op"
  },
  {
    "pattern": "∑|∏",
    "cls": "edsl-helper"
  },
  {
    "pattern": "°[CFR](?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-unit"
  },
  {
    "pattern": "℃|℉",
    "cls": "edsl-unit"
  },
  {
    "pattern": "°|²|³|√|⌊|⌋|⌈|⌉|‰|×|÷|·|⋅|−|≤|≥|≠|∞|↑|ᵀ|!(?!=)",
    "cls": "edsl-op"
  },
  {
    "pattern": "[⇥⭾↵⏎↩⮐]",
    "cls": "edsl-strescape"
  },
  {
    "pattern": "[½⅓¼¾⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞]",
    "cls": "edsl-number"
  },
  {
    "pattern": "[₀₁₂₃₄₅₆₇₈₉₊₋₍₎ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓᵦᵧᵨᵩᵪ͵]+",
    "cls": "edsl-subsup"
  },
  {
    "pattern": "[⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁽⁾˙ᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻ]+",
    "cls": "edsl-subsup"
  },
  {
    "pattern": "(?<![A-Za-z_0-9])([0-9][0-9a-fA-F]*)([₀₁₂₃₄₅₆₇₈₉]+)",
    "groups": [
      "edsl-number",
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![A-Za-z_0-9])([a-fA-F]+)(₁₆)",
    "groups": [
      "edsl-number",
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:R_jupiter|M_jupiter|M_earth|R_earth|M_moon|M_sun|T_sun|R_sun|R_gas|L_sun|Rᵍᵃˢ|inf|m_p|T_0|m_n|g_n|k_B|g_0|N_A|ε_0|q_e|µ_0|μ_0|m_e|μₒ|R☉|R⊙|kᵦ|M♃|mₑ|oo|Tₒ|Nᴬ|L☉|T☉|mₙ|R♃|gₒ|M☉|gₙ|R⊕|M⊙|M⊕|εₒ|pi|mₚ|L⊙|µₒ|qₑ|ħ|c|h|ℏ|π)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-physical"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:year_tropical|nautical_mile|hp_electrical|year_julian|GeV_per_c2|keV_per_c2|TeV_per_c2|MeV_per_c2|hp_metric|keV_per_c|TeV_per_c|eV_per_c2|MeV_per_c|GeV_per_c|prefix_d|fl_oz_uk|prefix_k|prefix_G|fl_oz_us|prefix_µ|prefix_μ|prefix_T|eV_per_c|prefix_M|prefix_p|ozf_inch|prefix_m|lbf_inch|prefix_c|prefix_n|coulomb|newton|deltaF|deltaK|deltaK|ton_uk|gal_uk|gal_us|deltaC|barrel|parsec|lbf_ft|ton_us|minute|nbarn|μbarn|ubarn|qt_uk|µbarn|litre|tonne|pt_uk|liter|abarn|pbarn|pt_us|qt_us|fbarn|month|inH2O|mbarn|grain|stone|week|mmHg|hour|mbar|knot|year|mile|slug|degR|dyne|kcal|degC|barn|degF|torr|yard|thou|inch|kgf|GPa|mNm|kph|Nmm|mol|lbm|ksi|THz|rad|GHz|µJy|Mpc|dam|kPa|ozt|keV|ozf|atm|MNm|Gyr|μJy|ppm|bar|Gpc|HMS|lbf|kyr|Myr|hms|kNm|BTU|amu|psi|MPa|day|Cal|cal|MeV|GeV|Ohm|kHz|PeV|MHz|ptc|TeV|kpc|uJy|EeV|mph|ptm|mJy|hPa|kWh|erg|mil|MV|km|mV|nV|eV|Hz|mm|kC|µm|mN|ΔK|au|hp|yr|kA|μN|MΩ|GΩ|mH|nA|μH|μF|nW|kN|ΔF|μV|nm|ng|cd|MW|µH|mL|pc|ns|pV|Da|Wb|pC|µg|ly|kW|kg|GN|μm|kΩ|oz|mC|pA|Jy|cm|ps|cc|µW|ft|nF|fs|GΩ|dm|fm|GJ|ΔC|mΩ|μs|µA|µC|MJ|kV|µs|mg|Wh|Nm|ms|μA|μW|hm|pH|µV|MΩ|μC|kJ|nC|pF|kΩ|µF|ΔK|MN|nH|μg|dL|pm|mA|µN|Pa|lb|mΩ|mF|sr|ks|GW|mW|J|W|V|H|F|C|Ω|T|s|Ω|K|m|A|K|N|S|Å|g|Å)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-unit"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:λ|ξ|ι|Θ|Ξ|ω|Ψ|υ|ε|ς|θ|κ|σ|δ|χ|γ|τ|ψ|μ|Λ|α|ρ|ο|Φ|β|ν|ζ|µ|η|Δ|φ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-greek"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:INR|CAD|DKK|EUR|NOK|CNY|NOK|HKD|DKK|CZK|AUD|DKK|CHF|SEK|USD|SEK|PLN|JPY|CZK|DKK|GBP|HKD)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-currency"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:positive_symbols|integer_symbols|complex_symbols|real_symbols|symbols)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-decl"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:update_currency_rates|clear_currency_cache|get_decimal_literals|to_fahrenheit_from_K|set_decimal_literals|to_fahrenheit_from_K|clear_protections|get_currency_rate|protect_constants|to_celsius_from_F|protect_si_units|to_kelvin_from_F|refresh_display|tolerance_unit|list_protected|register_radix|launch_palette|to_fahrenheit|rates_status|list_themes|protect_all|from_roman|sigfigs_of|to_celsius|print_view|from_degF|integrate|unprotect|from_degC|from_dB_p|to_kelvin|from_dB_v|plusminus|from_degR|permille|Rational|simplify|in_units|hardcopy|it_grade|measured|to_roman|parallel|protect|to_dB_v|polyfit|linefit|percent|display|to_dB_p|base10|factor|approx|expand|base16|series|phasor|Symbol|limit|roman|atanh|asinh|log10|base2|radix|floor|solve|acosh|base8|exact|atan2|shaft|diff|fact|atan|ceil|mean|sqrt|tanh|cosh|sinh|log2|plot|hole|acos|asin|oct|log|fit|tan|sym|dec|iso|sin|cos|Sig|mod|exp|bin|hex|fmt|pn|pv|pp|ln|Eq|Π|Γ|Σ|σ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-helper"
  },
  {
    "pattern": "([A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK][A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK]*)(ᵀ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "groups": [
      null,
      "edsl-op"
    ]
  },
  {
    "pattern": "([A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK][A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK]*)([ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓᵦᵧᵨᵩᵪᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻ]+)",
    "groups": [
      null,
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![\\w.])\\d+\\.(?![\\d.\\w])",
    "cls": "edsl-number"
  },
  {
    "pattern": "(\\.\\.\\s*)('(?:[^'\\\\\\n]|\\\\.)*'|\"(?:[^\"\\\\\\n]|\\\\.)*\")",
    "groups": [
      null,
      "edsl-string"
    ]
  },
  {
    "pattern": "[A-Za-z_][A-Za-z0-9_]*(?=\\s*\\.\\.(?!\\.))",
    "cls": "edsl-plain"
  },
  {
    "pattern": "(\\.\\.\\s*)([A-Za-z_][A-Za-z0-9_]*)",
    "groups": [
      null,
      "edsl-plain"
    ]
  },
  {
    "pattern": "(?<![\\w.])(?:0[xX][0-9a-fA-F_]+|0[bB][01_]+|0[oO][0-7_]+|\\d[\\d_]*\\.?[\\d_]*(?:[eE][+-]?\\d+)?[jJ]?|\\.\\d[\\d_]*(?:[eE][+-]?\\d+)?[jJ]?)",
    "cls": "edsl-number"
  },
  {
    "pattern": "(?<![=<>!:+\\-*/%&|^@])=(?!=)",
    "cls": "edsl-op"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:and|as|assert|async|await|break|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|nonlocal|not|or|pass|raise|return|try|while|with|yield)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-keyword"
  },
  {
    "pattern": "[+\\-*/%<>=!&|^~]+",
    "cls": "edsl-op"
  }
];
