// GENERATED by generate_rules.py from utils/Engineer_Style.py — do not edit.
// Re-run `python generate_rules.py` after changing the Pygments lexer.
export const DSL_RULES = [
  {
    "pattern": ":=|≔|←",
    "cls": "edsl-op"
  },
  {
    "pattern": "(\\d+)(\\.\\.)(?!\\.)",
    "groups": [
      "edsl-number",
      "edsl-op"
    ]
  },
  {
    "pattern": "(?<!\\.)(\\.\\.)(?!\\.)(\\s*)([+-]?)(\\d+(?:\\.\\d*)?(?:[eE][+-]?\\d+)?|\\.\\d+)",
    "groups": [
      "edsl-op",
      null,
      "edsl-op",
      "edsl-number"
    ]
  },
  {
    "pattern": "‥|(?<!\\.)\\.\\.(?!\\.)",
    "cls": "edsl-op"
  },
  {
    "pattern": "▶|▸",
    "cls": "edsl-op"
  },
  {
    "pattern": "→",
    "cls": "edsl-opword"
  },
  {
    "pattern": "ₜᵢₘₑ|ᵣₒₘₑ",
    "cls": "edsl-opword"
  },
  {
    "pattern": "‖|±|∠|≈",
    "cls": "edsl-op"
  },
  {
    "pattern": "∅",
    "cls": "edsl-constkw"
  },
  {
    "pattern": "∈|∉|∋|∌|∪|∩|∖|△|⊕|⊆|⊇|⊂|⊃",
    "cls": "edsl-op"
  },
  {
    "pattern": "∑|∏",
    "cls": "edsl-helper"
  },
  {
    "pattern": "°[CFR](?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-unit"
  },
  {
    "pattern": "℃|℉",
    "cls": "edsl-unit"
  },
  {
    "pattern": "°|²|³|√|⌊|⌋|⌈|⌉|‰|×|÷|·|⋅|−|≤|≥|≠|∞|↑|ᵀ|!(?!=)",
    "cls": "edsl-op"
  },
  {
    "pattern": "[⇥⭾↵⏎↩⮐]",
    "cls": "edsl-strescape"
  },
  {
    "pattern": "[½⅓¼¾⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞]",
    "cls": "edsl-number"
  },
  {
    "pattern": "[₀₁₂₃₄₅₆₇₈₉₊₋₍₎ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓᵦᵧᵨᵩᵪ͵]+",
    "cls": "edsl-subsup"
  },
  {
    "pattern": "[⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁽⁾˙ᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻ]+",
    "cls": "edsl-subsup"
  },
  {
    "pattern": "(?<![A-Za-z_0-9])([0-9][0-9a-fA-F]*)([₀₁₂₃₄₅₆₇₈₉]+)",
    "groups": [
      "edsl-number",
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![A-Za-z_0-9])([a-fA-F]+)(₁₆)",
    "groups": [
      "edsl-number",
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:M_jupiter|R_jupiter|R_earth|M_earth|M_moon|M_sun|T_sun|R_gas|L_sun|R_sun|Rᵍᵃˢ|ε_0|N_A|μ_0|g_0|g_n|T_0|q_e|inf|m_p|m_n|µ_0|k_B|m_e|R♃|mₑ|L☉|M⊙|mₚ|R⊕|qₑ|µₒ|mₙ|εₒ|T☉|Tₒ|gₙ|μₒ|Nᴬ|pi|R⊙|R☉|L⊙|M☉|oo|kᵦ|M⊕|M♃|gₒ|ℏ|π|c|ħ|h)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-physical"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:year_tropical|hp_electrical|nautical_mile|year_julian|keV_per_c2|TeV_per_c2|MeV_per_c2|GeV_per_c2|MeV_per_c|TeV_per_c|keV_per_c|eV_per_c2|GeV_per_c|hp_metric|prefix_d|prefix_G|lbf_inch|prefix_c|fl_oz_uk|prefix_p|prefix_M|prefix_µ|eV_per_c|prefix_μ|ozf_inch|fl_oz_us|prefix_m|prefix_k|prefix_n|prefix_T|coulomb|newton|barrel|parsec|deltaK|deltaK|gal_us|deltaC|ton_us|deltaF|gal_uk|minute|ton_uk|lbf_ft|ubarn|mbarn|qt_us|grain|μbarn|inH2O|fbarn|tonne|qt_uk|litre|µbarn|stone|pt_us|month|nbarn|pbarn|pt_uk|liter|abarn|degR|week|slug|degF|degC|torr|mbar|knot|mmHg|year|inch|hour|thou|mile|barn|kcal|yard|dyne|lbf|GHz|uJy|mil|kHz|TeV|ptc|MPa|Gyr|kgf|MNm|µJy|ksi|kpc|EeV|atm|kph|BTU|PeV|hPa|psi|ozf|Ohm|Gpc|μJy|mph|MHz|lbm|dam|Mpc|ppm|THz|mJy|rad|amu|keV|mNm|Myr|kNm|bar|HMS|GPa|hms|Nmm|MeV|kyr|erg|kPa|mol|ptm|day|kWh|ozt|GeV|Cal|cal|μm|nW|dL|ΔK|nA|fm|MW|cc|µC|mΩ|GJ|hp|Hz|Jy|au|pA|pF|ns|Wh|dm|pV|cm|nC|ΔC|hm|µF|Nm|pH|mg|nF|cd|kg|μF|μg|kΩ|µs|mA|μH|mC|ng|sr|pc|eV|GΩ|GW|MV|ΔK|kN|oz|µW|gf|mL|nm|mΩ|ks|mH|MJ|MΩ|µH|µV|yr|ms|mF|pm|μN|kV|Wb|mN|MΩ|Pa|μV|Da|kC|μW|MN|µm|nV|ft|μA|kΩ|µg|mV|GΩ|GN|fs|lb|mW|ly|pC|ps|km|kp|kJ|kW|kA|µA|mm|μs|ΔF|nH|μC|µN|N|J|g|Å|V|H|m|C|W|Å|Ω|K|F|K|A|s|Ω|T|S)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-unit"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:Θ|ε|ψ|ι|η|θ|ς|ν|Ψ|ρ|Δ|β|φ|Φ|ξ|λ|Ξ|δ|ω|ζ|σ|γ|µ|κ|μ|υ|ο|τ|α|χ|Λ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-greek"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:CZK|DKK|HKD|USD|SEK|CHF|CNY|CAD|SEK|JPY|GBP|PLN|DKK|INR|EUR|NOK|AUD|DKK|CZK|NOK|DKK|HKD)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-currency"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:positive_symbols|integer_symbols|complex_symbols|real_symbols|symbols)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-decl"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:update_currency_rates|clear_currency_cache|to_fahrenheit_from_K|get_decimal_literals|set_decimal_literals|to_fahrenheit_from_K|clear_protections|protect_constants|to_celsius_from_F|get_currency_rate|to_kelvin_from_F|protect_si_units|refresh_display|list_protected|register_radix|launch_palette|tolerance_unit|to_fahrenheit|rates_status|protect_all|list_themes|sigfigs_of|from_roman|to_celsius|print_view|from_dB_v|integrate|from_degF|to_kelvin|from_degR|from_dB_p|plusminus|unprotect|from_degC|in_units|it_grade|parallel|to_roman|Rational|simplify|hardcopy|measured|permille|to_dB_p|linefit|percent|polyfit|protect|display|to_dB_v|factor|base10|Symbol|phasor|expand|base16|series|approx|roman|limit|log10|asinh|solve|shaft|atan2|acosh|atanh|base8|exact|base2|floor|radix|plot|diff|tanh|mean|fact|asin|acos|log2|atan|cosh|ceil|hole|sinh|sqrt|cos|dec|iso|sym|fmt|hex|log|mod|Sig|sin|bin|tan|oct|exp|fit|pn|pp|ln|pv|Eq|Γ|Π|Σ|σ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-helper"
  },
  {
    "pattern": "([A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK][A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK]*)(ᵀ)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "groups": [
      null,
      "edsl-op"
    ]
  },
  {
    "pattern": "([A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK][A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK]*)([ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓᵦᵧᵨᵩᵪᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻ]+)",
    "groups": [
      null,
      "edsl-subsup"
    ]
  },
  {
    "pattern": "(?<![\\w.])\\d+\\.(?![\\d.\\w])",
    "cls": "edsl-number"
  },
  {
    "pattern": "(\\.\\.\\s*)('(?:[^'\\\\\\n]|\\\\.)*'|\"(?:[^\"\\\\\\n]|\\\\.)*\")",
    "groups": [
      null,
      "edsl-string"
    ]
  },
  {
    "pattern": "[A-Za-z_][A-Za-z0-9_]*(?=\\s*\\.\\.(?!\\.))",
    "cls": "edsl-plain"
  },
  {
    "pattern": "(\\.\\.\\s*)([A-Za-z_][A-Za-z0-9_]*)",
    "groups": [
      null,
      "edsl-plain"
    ]
  },
  {
    "pattern": "(?<![\\w.])(?:0[xX][0-9a-fA-F_]+|0[bB][01_]+|0[oO][0-7_]+|\\d[\\d_]*\\.?[\\d_]*(?:[eE][+-]?\\d+)?[jJ]?|\\.\\d[\\d_]*(?:[eE][+-]?\\d+)?[jJ]?)",
    "cls": "edsl-number"
  },
  {
    "pattern": "(?<![=<>!:+\\-*/%&|^@])=(?!=)",
    "cls": "edsl-op"
  },
  {
    "pattern": "(?<![A-Za-z_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])(?:and|as|assert|async|await|break|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|nonlocal|not|or|pass|raise|return|try|while|with|yield)(?![A-Za-z0-9_πμΩεℏΓΠΣσαβγδζηθικλνξορςτυφχψωΦΘΛΨΔÅΩµÅK])",
    "cls": "edsl-keyword"
  },
  {
    "pattern": "[+\\-*/%<>=!&|^~]+",
    "cls": "edsl-op"
  }
];
